{% set version = "0.2.8" %}
{% set name = "pydelatin" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3703dd37fc3fb5a2fc1ec681c530ccc95639885a93a5506fe057aed77d81fe6a

build:
  number: 1
  skip: true  # [py<36] [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - numpy
    - pybind11 >=2.5.0
    - glm
    - pip
  run:
    - python

test:
  imports:
    - pydelatin

about:
  home: https://github.com/kylebarron/pydelatin
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings to hmm for fast terrain mesh generation
  description: |
    A Python wrapper of hmm (of which Delatin is a port) for fast terrain mesh generation.
  doc_url: https://github.com/kylebarron/pydelatin
  dev_url: https://github.com/kylebarron/pydelatin

extra:
  recipe-maintainers:
    - davidbrochart
    - kylebarron
